language: julia
julia:
  - nightly
  - 1.4.2
  - 1.5.3
  
notifications:
  email: false
git:
  depth: 99999999

after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg; cd(Pkg.dir("DSTrees)); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("DSTrees")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  allow_failures:
    - julia: nightly
